### ISSUE TITLE
Upload folder with dot in name on start

### ISSUE THREAD

**Issue by landsman** [google-github-actions/upload-cloud-storage#102]
Hi guys,

I am uploading whole folder which contains folder: `.next`.
On Cloud Bucket this folder missing. I tried process 3x times, same result.

Is it bug or can I do some configuration to allow these hidden dot folders?

<img width="883" alt="Screenshot 2021-08-12 at 1 47 30" src="https://user-images.githubusercontent.com/3184228/129117786-e46f3771-fb5c-4beb-9e2e-ba9c864adda1.png">

<img width="785" alt="Screenshot 2021-08-12 at 1 48 38" src="https://user-images.githubusercontent.com/3184228/129117790-81f54f79-cf99-40ba-a61e-e70095ec3636.png">

Part of my workflow:

```
      - name: 'Copy assets out of the image'
        run: |
          mkdir ${{ env.ASSETS_FOLDER }}
          docker images
          export CID=$(docker create pay)
          docker cp $CID:/usr/src/.next ./${{ env.ASSETS_FOLDER }}
          cp -R public ./${{ env.ASSETS_FOLDER }}
          cd ${{ env.ASSETS_FOLDER }} && ls -la

      - name: 'Upload assets to GCP bucket, CDN'
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ env.GCP_SA_KEY }}
          path: ${{ env.ASSETS_FOLDER }}
          destination: ${{ env.GCP_BUCKET_PATH }}
          parent: false
```

**Comment by bharathkkb** [comment]
Hi @landsman 
We currently don't match dot files/folders. However we can add an option [here](https://github.com/google-github-actions/upload-cloud-storage/blob/73e61575aff029a3b7ee37ce9e4b1a0cb7113963/src/upload-helper.ts#L126) passing `dot: true`. 
https://github.com/mrmlnc/fast-glob#dot

Another workaround if you don't have additional dot files in `.next` could be to
```
- name: 'Upload assets to GCP bucket, CDN'
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ env.GCP_SA_KEY }}
          path: ${{ env.ASSETS_FOLDER }}/.next
          destination: ${{ env.GCP_BUCKET_PATH }}/.next
          parent: false
```
