### ISSUE TITLE
Synchronize folder as the bucket root

### ISSUE THREAD

**Issue by FFY00** [google-github-actions/upload-cloud-storage#11]
### TL;DR

Uploading a folder like this, will upload to `bucket-name/folder`. I want to synchronize the bucket root, `/path/to/folder` would be the root of my bucket. `/path/to/folder/a` would be `bucket-name/a`, not `bucket-name/folder/a`.
```yaml
steps:
  - id: upload-files
    uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
    with:
      path: /path/to/folder
      destination: bucket-name
```

### Design

**Action YAML**

I propose introducing a `root` input.
```yaml
steps:
  - id: upload-files
    uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
    with:
      path: /path/to/folder
      destination: bucket-name
      root: true
```

**Comment by sam-jg** [comment]
Is there any work around for this or any update @averikitsch?

**Comment by bharathkkb** [comment]
@sam-jg Thanks for your interest! I'll take a look

**Comment by sam-jg** [comment]
Work around for anyone else that finds this and is hosting some kind of static site. You can set the main page of the bucket to something else by changing the `MainPageSuffix`

Essentially means you can change the entry point from `bucket-name/index.html` to `bucket-name/some-path/some-file`. For most static sites you would likely want to set it to `public/index.html`

https://cloud.google.com/storage/docs/hosting-static-website#specialty-pages

Still think it is a worthwhile change though @bharathkkb, thanks.

**Comment by tobbbles** [comment]
It's a shame this isn't fixed, to me this action is completely unusable without being able to specify this, the best workaround right now is this for me :disappointed: 

```
- name: upload
  run: gsutil cp -r out/* gs://${{ env.BUCKET }}/
```

**Comment by carlodevil** [comment]
Any news here? Would really love this functionality.

**Comment by aglasson** [comment]
I ended up here because I noticed this is the exact same behaviour as for the `New-GcsObject` Powershell Cmdlet with `-Folder` parameter. Which has been annoying me.

Just adding my 2c here from my observations on the core reason this functionality is the way it is and how I intend to solve the problem which might provide insight when someone goes to implement/solve this.

Reviewing the documentation on the Google Cloud SDK commandline utils for Google Storage (gsutil) which I would suspect the Powershell Cmdlet leverages and perhaps this also. That seems to be the expected behaviour there:
>For example, if dir1/dir2 contains the file a/b/c, then the following command creates the object gs://my-bucket/dir2/a/b/c
Having used commandline functions to upload files to both Azure Blob and AWS S3, this GCP implementation definitely seems to do it differently.

My solution, using Powershell, to simply as possible place the contents of a folder into the root of a GCP Storage Bucket will be along the lines of:
`$FilesAndDirectoriesInsideSourceFolder  |  If type directory  {upload using the folder method as demonstrated}`
`$FilesAndDirectoriesInsideSourceFolder  |  If type file  {upload straight into bucket}`
That will produce bucket contents in the same structure as the source folder.

So @FFY00 suggested implementation looks sensible just be mindful some logic beyond simply using the underlying utility differently will probably be required.

**Comment by bharathkkb** [comment]
@FFY00 @sam-jg @tobbbles @aglasson 
Apologies for the long delay. I have added a `parent` flag which should let you control this now. Also added some docs on potential scenarios here https://github.com/google-github-actions/upload-cloud-storage#upload-to-bucket-root

With `parent:false` and `path:/path/to/folder`, `/path/to/folder/a` should now be uploaded to `bucket-name/a`
```
steps:
  - id: upload-files
    uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
    with:
      path: /path/to/folder
      parent: false
      destination: bucket-name
```

It would be awesome to get any feedback if this helps.

**Comment by gonz01d** [comment]
@bharathkkb 
I'm trying to use the latest version (`google-github-actions/upload-cloud-storage@main`) and make use of the `parent: false` flag to do a root copy but what I'm finding is the last folder in the path is still being used in the destination copied path:

e.g.
```
with:
      path: /path/to/folder
      parent: false
      destination: bucket-name
```

Using your example path ` /path/to/folder` - my files are being copied as `bucket-name/folder/blah.txt` whereas I'm expecting `bucket-name/blah.txt`

If it helps I can pass on my logs or enable debug and pass those logs on to you

**Comment by bharathkkb** [comment]
Hi @gonz01d 
Thanks for the report! Logs would be helpful and if your repo is public I can take a look at that too.

I tried a quick check in https://github.com/bharathkkb/test-upload-gcs-action
where I have a dir like `nested/in/here/hello.txt` and action configured as
```
uses: google-github-actions/upload-cloud-storage@main
        with:
          path: nested/in/here
          parent: false
```
This seems to upload it as expected to `gs://$BUCKET/hello.txt`
