### ISSUE TITLE
Relative path does not find any files

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [google-github-actions/upload-cloud-storage#13]
### TL;DR

**Expected behavior**
The root path should be the same as the checkout path (at least intuitively). Instead the file is not found when uploading. Perhaps a more helpful error message would be printing the full path of the attempted upload.

**Observed behavior**
File not found error.

### Reproduction

**Action YAML**
```
name: test
on: push
jobs:
  push:
    name: Push to GCS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/upload-cloud-storage@main
      with:
        credentials: ${{ secrets.TEST }}
        path: ../test
        destination: test
```

**Repository**
https://github.com/GuessWhoSamFoo/gcs-push-test/

**Additional information**
n/a
