### ISSUE TITLE
Setting gzip to false

### ISSUE THREAD

**Issue by omrihq** [google-github-actions/upload-cloud-storage#14]
### TL;DR
Uploading to GCS using upload-cloud-storage actions passes `gzip: true` as a default, can this be an option?

### Design

**Action YAML**
In this line, the default is set to `gzip: true`, I'd like to be able to set this. 
https://github.com/google-github-actions/upload-cloud-storage/blob/3d447c22006c4a60e679e1e4bd435062c5c7a995/src/upload-helper.ts#L55

```yaml
            -   name: Upload files
                id: upload-files
                uses: google-github-actions/upload-cloud-storage@main
                with:
                    path: foo
                    destination: bucketname 
                    gzip: false
```
