### ISSUE TITLE
Cache-Control header not applied

### ISSUE THREAD

**Issue by iChip** [google-github-actions/upload-cloud-storage#151]
### TL;DR

Unable to apply cache-control header
**Expected behavior**

Uploaded file in GCS contains expected metadata

**Observed behavior**

Uploaded file does not have cache-control set. In my action, I see:
> Unexpected input(s) 'headers', valid inputs are ['credentials', 'path', 'destination', 'gzip', 'resumable', 'predefinedAcl', 'parent', 'glob', 'concurrency']

### Reproduction

**Action YAML**

```yaml
# Paste your complete GitHub Actions YAML here, removing
      - name: Upload app files
        uses: google-github-actions/upload-cloud-storage@v0.4.0
        with:
          path: ${{ env.BUILT_APP_DIR }}
          parent: false
          destination: my-bucket-name
          glob: '**/*'
          gzip: true
          headers: |-
            cache-control: public, max-age=300, must-revalidate
# any sensitive values.
```

**Additional information**
