### ISSUE TITLE
Exception uploading static assets to GCS

### ISSUE THREAD

**Issue by iChip** [google-github-actions/upload-cloud-storage#178]
### TL;DR

**Expected behavior**

Successful upload. 
**Observed behavior**

Exception and failed action.

```json
{"$id":"1","innerException":null,"message":"Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.","typeName":"System.InvalidOperationException, System.Private.CoreLib, Version=14.0.0.0, Culture=neutral, PublicKeyToken=XXXXXX","typeKey":"InvalidOperationException","errorCode":0,"eventId":0}
```

### Reproduction

**Action YAML**

```yaml
# Paste your complete GitHub Actions YAML here, removing
# any sensitive values.
      - name: Upload assets
        uses: google-github-actions/upload-cloud-storage@v0.5.0
        with:
          path: ${{ env.BUILT_APP_DIR }}
          parent: false
          destination: ${{ env.GCS_BUCKET }}
          glob: 'assets/*'
          gzip: true
          headers: |-
            cache-control: public,max-age=31536000,immutable
```

**Repository**

**Additional information**
