### ISSUE TITLE
How to use the folder/files created in previous step

### ISSUE THREAD

**Issue by blackout1208** [google-github-actions/upload-cloud-storage#179]
I'm looking to upload all static content built-in in one step and upload it into a bucket on the following step. As I'm doing, it doesn't find my content.

Any guidance on how I can make it happen?

```
  - name: Build gulpfile
      id: "gulpfile"
      run: npx gulp

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ secrets.GCP_CDN_WORKLOAD_IDENTITY }}
        service_account: ${{ secrets.GCP_CDN_SA_CREDENTIALS }}

    - name: 'test'
      run: |
        echo "content here:"
        ls ./public #all content is printed here

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: ./public
        destination: 'static-bucket'
        parent: false
```
