### ISSUE TITLE
action ignores working-directory default

### ISSUE THREAD

**Issue by legion-11** [google-github-actions/upload-cloud-storage#190]
### Question
When you specify defaults: working-directory, action ignores it and runs from the root directory. Is it intended behavior?

My YAML file:

```
name: GCP Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    defaults:
      run:
        working-directory: ./app

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: 'Configure GCP credentials'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Upload'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: '${{ env.SOURCE_DIR }}'
          destination: '${{ secrets.GCP_BUCKET_NAME }}'
          parent: false

env:
  SOURCE_DIR: app/build
```
Since I specified working-directory: ./app why does the SOURCE_DIR still have to be app/build?
