### ISSUE TITLE
Allow filtering files

### ISSUE THREAD

**Issue by jordanpotter** [google-github-actions/upload-cloud-storage#20]
### TL;DR
Allow filtering files by specifying a glob pattern. This would be useful for static websites that generate files during their build phase that aren't meant for public consumption, such as source maps.

### Design

**Action YAML**
The user could specify a glob pattern. Only files that match that glob pattern are uploaded.

```yaml
steps:
  - id: upload-files
    uses: google-github-actions/upload-cloud-storage@main
    with:
      path: /path/to/folder
      match: **/!(*.map)
      destination: bucket-name
```

**Resources**
N/A

**Additional information**
N/A
