### ISSUE TITLE
Improve documentation about folders uploading

### ISSUE THREAD

**Issue by rascontextual** [google-github-actions/upload-cloud-storage#23]
### TL;DR

I need to upload a folder with some DAGS (python3 scripts), I am able to use relative paths, or absolute paths, but what is default path? In the following example:
```
├── README.md
├── requeriments.txt
└── tarea1
    └── dag.py
```
The default path start  on README.md level, or in .github/workflows level?
### Design

**Action YAML**

```
name: update-dags
on:
  push:
    branches:
    - main
  # Simplemente hay que sincronizar
jobs:
  sincronizar:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Sync dag folder
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: tarea1
          destination: ${{ secrets.GCP_BUCKET_NAME }}
```

**Comment by bharathkkb** [comment]
Hi @rascontextual 
By default you will be in `GITHUB_WORKSPACE`. If you are using `actions/checkout` this will have the repo checked out. In your sample workflow I do not see `actions/checkout` so this means you are not cloning your repo and hence `GITHUB_WORKSPACE` will be empty. If you add checkout, then you can upload `tarea1` like
```

      - name: Sync dag folder
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: tarea1
          destination: ${{ secrets.GCP_BUCKET_NAME }}
```

**Comment by mrskug** [comment]
As a small FYI this changed the default behavior for upload paths as this now uploads to the full path specified and not just the last folder.

Previously this:
```yaml
steps:
  - id: upload-files
    uses: google-github-actions/upload-cloud-storage@main
    with:
      path: myfolder/foo
      destination: bucket-name
```

would have uploaded just the folder `foo` as `gs://bucket-name/foo` 
but as of this change it now defaults to uploading to `gs://bucket-name/myfolder/foo`

This caused some confusion to say the least...

**Comment by jvelezos** [comment]
Same here, this change caused a problem in my project, since now the path is used both for input and for output.

**Comment by bharathkkb** [comment]
Hi @mrskug @jvelezos 
Hopefully the new behavior is more explicit. To preserve the previous behavior you can do
```yaml
steps:
  - id: upload-files
    uses: google-github-actions/upload-cloud-storage@main
    with:
      path: myfolder/foo
      destination: bucket-name/foo
      parent: false
```
as [documented here](https://github.com/google-github-actions/upload-cloud-storage#:~:text=name/file2.txt-,Optionally%2C%20you%20can%20also%20specify%20a%20prefix%20in%20destination,-.). Feel free to reopen if you have any issues.
