### ISSUE TITLE
Suddenly began to fail with the error: path should be a `path.relative()`d string

### ISSUE THREAD

**Issue by AF250329** [google-github-actions/upload-cloud-storage#248]
### TL;DR

I've been using 'upload-cloud-storage' in multiple projects for a while now, and everything was fine until recently, when it began to fail with the following error:

```
Error: google-github-actions/upload-cloud-storage failed with path should be a `path.relative()`d string, but got "D:\a\project\archive.1.0.8132.27186-b6b5283.tar.gz"
```

Here is relevant parts in my Github workflow:

```yml
...
...
jobs:
    build:
        name: Compile and package
        runs-on: windows-latest
...
...
         -
            name: Collect UnitTests files
            id: collect-test-files
            env:
                PRODUCT_VERSION: ${{ steps.create-version-id.outputs.version }}
            run: |
                $fileName = "archive.$($env:PRODUCT_VERSION).tar.gz"

                Start-Process -NoNewWindow -FilePath 'tar.exe' -ArgumentList  "-cz", "-f $fileName", ".\UnitTestFiles" -Wait;

                $fileName = "$(Get-Location)\$fileName"

                Write-Host "::set-output name=unittest_file::$fileName"
        -
            name: Authenticate to Google Cloud
            uses: 'google-github-actions/auth@v0'
            with:
                credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        -
            name: Upload to Google Storage bucket
            uses: 'google-github-actions/upload-cloud-storage@v0'
            with:
                path: '${{ steps.collect-test-files.outputs.unittest_file }}'
                destination: 'integration-tests-cache'
                parent: false

```

What I can do about it ?

### Expected behavior

File should be uploaded to Google Storage even if provided absolute path and not just relative

### Observed behavior

Upload process crashed with error and crashed the workflow

### Action YAML

```yaml
...
...
jobs:
    build:
        name: Compile and package
        runs-on: windows-latest
...
...
         -
            name: Collect UnitTests files
            id: collect-test-files
            env:
                PRODUCT_VERSION: ${{ steps.create-version-id.outputs.version }}
            run: |
                $fileName = "archive.$($env:PRODUCT_VERSION).tar.gz"

                Start-Process -NoNewWindow -FilePath 'tar.exe' -ArgumentList  "-cz", "-f $fileName", ".\UnitTestFiles" -Wait;

                $fileName = "$(Get-Location)\$fileName"

                Write-Host "::set-output name=unittest_file::$fileName"
        -
            name: Authenticate to Google Cloud
            uses: 'google-github-actions/auth@v0'
            with:
                credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        -
            name: Upload to Google Storage bucket
            uses: 'google-github-actions/upload-cloud-storage@v0'
            with:
                path: '${{ steps.collect-test-files.outputs.unittest_file }}'
                destination: 'integration-tests-cache'
                parent: false



Sorry - it is a private repo - could not paste the whole workflow
```

### Additional information

I am running on Windows 2022 Github action runner

**Comment by AF250329** [comment]
Mmmmm... I must be missed the party but now I understand that Github removed Google Cloud SDK completely from Windows-2022 runner (https://github.com/actions/virtual-environments/commit/a2d76d2a0e52f14897950ac014385ac71a5c9290#diff-0f0deef55edf9ac41fe9db1cd386e44aac4536569e49e147e8fdc52457ca8dedL92). 

I don't know who is throwing this exception but I understand now that I need to install Google Cloud SDK first

**Comment by sethvargo** [comment]
Hi @AF250329 

Sorry about that. Could you try pinning `upload-cloud-storage@v0.8.0` and see if the issue persists? If it goes away, that means something in our latest release changed accidentially.

**Comment by nathanklick** [comment]
@sethvargo We are also seeing the same issue with our pipelines running on Ubuntu Linux both using self hosted runners and Github hosted runners. It does appear that the `v0.9.0` may be the culprit; however, downgrading to `v0.8.0` we see the error in #241 manifest instead.

I am testing the `v0.7.0` tag now and will update you as soon as the pipeline fails or finishes.

**Comment by nathanklick** [comment]
@sethvargo The `v0.7.0` tag works just fine. It is possible that the failure that manifested in `v0.8.0` as described in #241 and this issue are related or the same issue.

**Comment by aznashwan** [comment]
Can confirm we've just had this happen when using `@v0` in the [containerd CI here](https://github.com/containerd/containerd/runs/5878461244?check_suite_focus=true#step:26:32).

We've neither changed the GitHub runner (`ubuntu-latest`), nor the paths we upload to.

Testing with `@0.8.0` soon and will let you know,  but it already looks like one of the dependencies which recently got updated in #246 is the most likely culprit...

**Comment by sethvargo** [comment]
@nathanklick or @aznashwan could either of you share a complete action.yml and local file layout for what you're uploading? I'm highly suspicious of https://github.com/google-github-actions/upload-cloud-storage/commit/0715ae527180418bb29f3055035821805f8b3344, since that's where the error is coming from. I'd like to try and create a test and fix for this.

**Comment by aznashwan** [comment]
@sethvargo absolutely, on our end we have [this workflow](https://github.com/containerd/containerd/blob/main/.github/workflows/windows-periodic.yml) which just use `upload-cloud-storage` to upload a handful of text files, all referenced via absolute path, which you can see listed in [the Upload* tasks in this successful run](https://github.com/aznashwan/containerd/runs/5883582618?check_suite_focus=true#step:26:1) in which I had [pinned 0.8.0] (https://github.com/aznashwan/containerd/actions/runs/2114594336/workflow#L238-L246).

The workflow's purpose is to build and test containerd on Windows, so most of the tasks within are irrelevant to the case at hand. To give a quick summary, each matrix entry runs on the `ubuntu-latest` GitHub runner and creates a Windows VM on Azure on which the building/testing is actually done, after which it pulls the run logs (all plain text files) to the GitHub runner where they're passed via absolute path to `upload-cloud-storage`.

**Comment by sethvargo** [comment]
@aznashwan @nathanklick could you try:

```yaml
uses: 'google-github-actions/upload-cloud-storage@592bd71309a7c7ba19e85a0d4df4e311bf3fd053'
```

and report back please?

**Comment by nathanklick** [comment]
Thanks @sethvargo, will kick off a test right now.

**Comment by nathanklick** [comment]
@sethvargo This build also fails in a similar fashion as the `v0.9.0` tag. The `v0.7.0` tag works with no issues.  The `v0.8.0` tag fails half-way through the upload; whereas the `v0.9.0` tag and the new version you gave above fail before uploading any files.

My folder structure in this job is simply a single folder that contains a bunch of tiny JUnit report XML files under the following path: `~/junit-reports`

**New Version Failure:**
```
Error: google-github-actions/upload-cloud-storage failed with: path should be a `path.relative()`d string, but got "../../../../home/runner/junit-reports/TEST-com.swirlds.common.test.AddressBookTest.xml"
```

**Tag v0.8.0 Failure:**
```
Error: google-github-actions/upload-cloud-storage failed with error code [object Object]
```

**Tag v0.9.0 Failure:**
```
Error: google-github-actions/upload-cloud-storage failed with path should be a `path.relative()`d string, but got "/home/runner/junit-reports/TEST-com.swirlds.common.test.AddressBookTest.xml"
```

Snippet from my pipeline:
```
     - name: Run JUnit Tests
        if: ${{ inputs.enable-unit-tests && steps.maven-deploy.conclusion == 'success' && !cancelled() && always() }}
        run: ./mvnw verify

      - name: Publish JUnit Test Report
        uses: dorny/test-reporter@v1
        if: ${{ inputs.enable-unit-tests && steps.maven-deploy.conclusion == 'success' && !cancelled() && always() }}
        with:
          name: JUnit Test Report
          reporter: java-junit
          max-annotations: 50
          list-suites: failed
          list-tests: failed
          path: '**/target/surefire-reports/TEST-*.xml'

      - name: Collect JUnit Reports
        id: junit-reports
        if: ${{ inputs.enable-unit-tests && steps.maven-deploy.conclusion == 'success' && !cancelled() && always() }}
        run: |
          [[ -d "${HOME}/junit-reports" ]] || mkdir -p "${HOME}/junit-reports"
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp -v {} "${HOME}/junit-reports" \;
          echo "::set-output name=path::${HOME}/junit-reports"

      - name: Compute JUnit Bucket Prefix
        id: junit-bucket
        if: ${{ inputs.enable-unit-tests && steps.maven-deploy.conclusion == 'success' && !cancelled() && always() }}
        run: |
          PREFIX="${{ github.repository }}/${{ github.actor }}/${{ github.ref_name }}/$(echo "${{ github.workflow }}" | sha256sum | cut -d ' ' -f 1)/${{ github.run_number }}/${{ github.run_attempt }}"
          echo "::set-output name=prefix::${PREFIX}"

      - name: Upload JUnit Reports
        uses: google-github-actions/upload-cloud-storage@592bd71309a7c7ba19e85a0d4df4e311bf3fd053
#        uses: google-github-actions/upload-cloud-storage@v0.7.0
        if: ${{ inputs.enable-unit-tests && steps.maven-deploy.conclusion == 'success' && !cancelled() && always() }}
        with:
          parent: false
          path: ${{ steps.junit-reports.outputs.path }}
          destination: ${{ inputs.junit-report-bucket }}/${{ steps.junit-bucket.outputs.prefix }}
```
