### ISSUE TITLE
Getting error while uploading path.relative()

### ISSUE THREAD

**Issue by amansingh14** [google-github-actions/upload-cloud-storage#252]
### TL;DR

`Error: google-github-actions/upload-cloud-storage failed with path should be a `path.relative()`d string,`

I tried with relative as well as absolute path both the paths are not working.

```    
   - name: 'upload file'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: '/tmp/test.txt'
          destination: 'bucket_name/test.txt'
```

```
    - name: 'upload file'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: '../../../tmp/test.txt'
          destination: 'bucket_name/test.txt'
```

### Action YAML

```yaml
- name: 'upload file'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: '/tmp/test.txt'
          destination: 'bucket_name/test.txt'
```

```
    - name: 'upload file'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: '../../../tmp/test.txt'
          destination: 'bucket_name/test.txt'
```
```


### Log output

```text
Error: google-github-actions/upload-cloud-storage failed with path should be a `path.relative()`d string,
```
