### ISSUE TITLE
After refactor in version v0.10.0 mime types are often wrong

### ISSUE THREAD

**Issue by spathon** [google-github-actions/upload-cloud-storage#258]
### TL;DR

In version `v0.10.0` all files our files get the mime type `image/svg+xml` in the GCP bucket.

### Expected behavior

Previous version got the correct mime type based on file.

### Observed behavior

All files (.js, .css etc) all get `image/svg+xml` as mime typ in GCP

### Action YAML

```yaml
name: Deploy production

on:
  push:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13'

      - name: Install
        run: npm i

      - name: Build
        run: npm run build

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_PRODUCTION }}'

      - id: 'upload-build-folder'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: './build'
          destination: 'path/to/folder'
          parent: false
```
