### ISSUE TITLE
set-output is deprecated

### ISSUE THREAD

**Issue by AngellusMortis** [google-github-actions/upload-cloud-storage#292]
### TL;DR

Running the `google-github-actions/upload-cloud-storage@v0` action produces the following warning:

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Link from message: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### Expected behavior

Warning should not occur.

### Action YAML

```yaml
on:
  workflow_dispatch:

jobs:
  static:
    runs-on: ubuntu-latest

    steps:
    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: './path/to/file'
        destination: 'bucket'
```
