### ISSUE TITLE
Looks like 0.10.4 hasn't been released.

### ISSUE THREAD

**Issue by Byeong-jun-Kim** [google-github-actions/upload-cloud-storage#298]
### TL;DR

https://github.com/google-github-actions/auth/issues/235
As I mentioned here, it looks like 0.10.4 hasn't been released.

https://github.com/marketplace/actions/cloud-storage-uploader
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/75416321/197858202-6762e5a6-f394-433c-9e6d-76fb4565596d.png">

### Action YAML

```yaml
- name: Upload apk file
      uses: google-github-actions/upload-cloud-storage@v0.10.4
      with:
        path: asdf
        destination: asdf
        parent: false
```
