### ISSUE TITLE
Getting artifact upload public URL in steps after upload

### ISSUE THREAD

**Issue by AaronMT** [google-github-actions/upload-cloud-storage#30]
Hello,

In a GitHub Actions job, after ```google-github-actions/upload-cloud-storage@main``` step, I would like to get the public URL of the uploaded artifact from the previous step.

The idea is a job using the following steps as an example:

* Build a binary
* Upload binary as an artifact
* Fire off a Slack message with a public URL of said binary

How would you get the public URL of the artifact in a subsequent step?

```Yaml
- uses: google-github-actions/upload-cloud-storage@main
   name: Upload Artifact (json) to Google Cloud Storage
   with: 
       path: file
       destination:  bucket/output
       env-pub: FOOBAR
  -name: Use URL for something
    run: echo "${{ env.FOOBAR }}"
```
The last command would give me a public URL to the uploaded artifact.

**Comment by jakub-bacic** [comment]
That should do the trick:

```yaml
steps:
  - id: upload-file
    name: Upload Artifact (json) to Google Cloud Storage
    uses: google-github-actions/upload-cloud-storage@main
    with:
      path: file
      destination:  bucket/output

  - name: Get public URL
    run: echo "PUBLIC_URL=https://storage.googleapis.com/${{steps.upload-files.outputs.uploaded}}" | sed 's|gs://||' >> $GITHUB_ENV

  - name: Use URL for something
    run: echo "${{ env.PUBLIC_URL }}"
```
