### ISSUE TITLE
Upload fails with: triggerUncaughtException(err, true /* fromPromise */);

### ISSUE THREAD

**Issue by cwolf24** [google-github-actions/upload-cloud-storage#308]
### TL;DR

Hello,

unfortunately i sometimes get an uncaught exception while uploading a testreport (~ 500 files)
See log output for exception details. As i see in the log, that several files are uploaded before the exception appears.
It happens from time to time. Maybe 1/10 tries.

Do you know if it is possible to enable a retry or handle the exception within your package?
That would be awesome to have this Job always pass. 🙂  

### Expected behavior

uploading files always works

### Observed behavior

upload is not successful due to the exception

### Action YAML

```yaml
upload-report:
    name: Upload Report
    if: (success() || failure()) && needs.test-integration.result != 'skipped'
    runs-on: ubuntu-latest
    environment:
      name: dev-cluster
    env:
      JOB_NAME: ${{github.job}}
    needs:
      - test-integration
    steps:
      - name: Archive Report Download
        uses: actions/download-artifact@v3
        with:
          path: tests/output/allure-report
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1.0.0
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.*** }}
          service_account: ${{ secrets.***}}
      - name: Authenticate to GKE cluster
        uses: google-github-actions/get-gke-credentials@v1.0.1
        with:
          cluster_name: ${{ secrets.*** }}
          location: ${{ secrets.*** }}
          use_internal_ip: true
      - name: Upload Report
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: tests/output/allure-report
          parent: false
          destination: ${{ env.BUCKET_NAME }}/${{ env.BUCKET_PATH }}
          concurrency: 50
```

### Log output

```text
Run google-github-actions/upload-cloud-storage@v1
Upload files
Uploading /tests/output/allure-report/test-integration/index.html to gs://***
...
Uploading /tests/output/allure-report/test-integration/history/retry-trend.json
Uploading /tests/output/allure-report/test-integration/history/history.json to gs://***
Uploading /tests/output/allure-report/test-integration/history/history-trend.json to gs://***
Uploading /tests/output/allure-report/test-integration/history/duration-trend.json to gs://***

 node:internal/process/promises:279
              triggerUncaughtException(err, true /* fromPromise */);
              ^
  FetchError: request to https://pipelines.actions.githubusercontent.com/... failed, reason: 
connect ETIMEDOUT 13.107.42.16:443
      at ClientRequest.<anonymous> (/home/runner/work/_actions/google-github-actions/upload-cloud-storage/v1/dist/index.js:201:57777)
      at ClientRequest.emit (node:events:527:28)
      at TLSSocket.socketErrorListener (node:_http_client:454:9)
      at TLSSocket.emit (node:events:527:28)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
```
