### ISSUE TITLE
gha-creds file getting pushed to the storage

### ISSUE THREAD

**Issue by harshitaXerox** [google-github-actions/upload-cloud-storage#311]
### TL;DR

Hi Team,

The gha-creds* file is also getting pushed to the cloud storage along with the build folder.

Could you please check and let us know if by any chance we can ignore this file.

 - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
           credentials_json: '${{ secrets.***}}'
           export_environment_variables: false
              
      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: '.'
          destination: 'carear-metroplex-portal' 
          parent: false
          process_gcloudignore: true   

Thanks
Harshita

### Action YAML

```yaml
name: Move to Firebase storage on workflow_dispatch
'on': 
 workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'metroplex'
        
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: main
      - name: Checkout ex builder repo
        uses: actions/checkout@v3
        with:
          repository: carear-io/CareARExperienceBuilder
          path: CareARExperienceBuilder
          ref: ${{ github.event.inputs.experiencebuilderbranch  }} 
          token: ${{ secrets.GIT_ACCESSTOKEN_CICD }}
    
 [[ here we have the logic to build the app]
       
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: ./main/build
          
  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download the build output
        uses: actions/download-artifact@v3
        with:
          name: build

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
           credentials_json: '${{ secrets.FIREBASE_CAREAR_METROPLEX}}'    

      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: '.'
          destination: 'carear-metroplex-portal' 
          parent: false
          process_gcloudignore: true
```
