### ISSUE TITLE
Error during upload: the offset is lower than the number of bytes written.

### ISSUE THREAD

**Issue by cwolf24** [google-github-actions/upload-cloud-storage#331]
### TL;DR

An unexpected Error: `the offset is lower than the number of bytes written. ` appears when we upload files.

### Expected behavior

Uploading the files (test reports) always works.

### Observed behavior

Today, the mentioned error appears already two times when we tried to upload our files (test reports). See log output for error details

### Action YAML

```yaml
- name: Authenticate to GCP
        uses: google-github-actions/auth@v1.1.1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_OIDC_ID_PROVIDER }}
          service_account: ${{ secrets.GCP_OIDC_SA}}
      - name: Authenticate to GKE cluster
        uses: google-github-actions/get-gke-credentials@v1.0.2
        with:
          cluster_name: ${{ secrets.GCP_K8S_CLUSTER }}
          location: ${{ secrets.GCP_K8S_REGION }}
          use_internal_ip: true 
      - name: Upload Report
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: tests/output/allure-report
          parent: false
          destination: ${{ env.GCP_BUCKET_NAME }}/${{ env.GCP_BUCKET_PATH }}
          concurrency: 50
```

### Log output

```text
Error: google-github-actions/upload-cloud-storage failed with: the offset is lower than the number of bytes written. The server has 0 bytes and while 10 bytes has been uploaded - thus 10 bytes are missing. Stopping as this could result in data loss. Initiate a new upload to continue.
  node:internal/process/promises:279
              triggerUncaughtException(err, true /* fromPromise */);
              ^
  
  RangeError: The offset is lower than the number of bytes written. The server has 0 bytes and while 10 bytes has been uploaded - thus 10 bytes are missing. Stopping as this could result in data loss. Initiate a new upload to continue.
      at Upload.startUploading (/home/runner/work/_actions/google-github-actions/upload-cloud-storage/v1/dist/index.js:139:6312)
      at Upload.continueUploading (/home/runner/work/_actions/google-github-actions/upload-cloud-storage/v1/dist/index.js:139:5810)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```


### Additional information

So far this issue has only been seen today.
