### ISSUE TITLE
Support action issues a warning instead of fail when no file exist in the given path

### ISSUE THREAD

**Issue by capri-xiyue** [google-github-actions/upload-cloud-storage#332]
### TL;DR

Currently, it will fail when no file exist in the given path with error `google-github-actions/upload-cloud-storage failed with: ENOENT: no such file or directory`. It will be useful that users have the option to choose whether the action should fail or issue a warning when no file exists.

**Comment by sethvargo** [comment]
Hey @capri-xiyue - I think it would be better to skip the step altogether with an `if` statement:

```yaml
- steps:
  - uses: 'google-github-actions/upload-cloud-strorage@v1'
    if: '${{ hashFiles(''./path/*'') == '''' }}'
```

That is strictly more efficient because then GitHub doesn't even _download_ the action source.
