### ISSUE TITLE
Glob does not work correctly

### ISSUE THREAD

**Issue by dr-vortex** [google-github-actions/upload-cloud-storage#337]
### TL;DR

Using a glob like `./dir/my-app*` yields `Error: google-github-actions/upload-cloud-storage failed with: ENOENT: no such file or directory, lstat '/home/runner/work/repo/repo/dir/my-app*'`, even though `dir/my-app.exe` exists.

### Expected behavior

The glob pattern to resolve into the files it matches

### Observed behavior

It treated the glob pattern like a file, without resolving it first

### Action YAML

```yaml
name: Continuous Integration

on:
    push:
        branches:
            - main

jobs:
    ci:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        name: ${{ matrix.os }}
        permissions:
            contents: read
            id-token: write
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Formatting
              run: npm run format:check

            - name: Linting
              run: npm run lint

            # Once tests are added
            #-name: Test
            # run: npm run test

            - name: Build client
              run: npm run build:client

            - name: Build server
              run: npm run build:server

            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v1
              with:
                  workload_identity_provider: projects/195808230594/locations/global/workloadIdentityPools/github/providers/oidc
                  service_account: github-actions@blankstorm.iam.gserviceaccount.com

            - name: Upload build
              uses: google-github-actions/upload-cloud-storage@v1
              with:
                  path: ./dist/blankstorm-client*
                  destination: drvortex.dev
                  parent: false
```

### Log output

https://github.com/dr-vortex/blankstorm/actions/runs/5700838637/job/15451017276

**Comment by sethvargo** [comment]
Hi @dr-vortex - please share your [debug output](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging). Also, it appears you are running this on 3 OSes (Linux, Mac, Windows); is that intended? At present, that matrix runs in parallel and all 3 OSes are going to try and upload different files to the same bucket and paths.

**Comment by dr-vortex** [comment]
Here is the run with debug logging: https://github.com/dr-vortex/blankstorm/actions/runs/5700838637/job/15451347134

> Also, it appears you are running this on 3 OSes (Linux, Mac, Windows); is that intended? At present, that matrix runs in parallel and all 3 OSes are going to try and upload different files to the same bucket and paths.

Yes, I run tests on each platform, which uploads files specific to that platform.

**Comment by sethvargo** [comment]
Hi @dr-vortex - that's the runner logs. I need the [debug logs](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging), which requires setting a secret of `ACTIONS_STEP_DEBUG` to `true` and re-running the job. You should a LOT of output including "Computed absoluteRoot from" and "Found XX files".

> Yes, I run tests on each platform, which uploads files specific to that platform.

Your current upload action has no namespace by matrix. That means files that are generated that have the same name will be overwritten in a non-deterministic way (depending on which runner runs first):

```yaml
- name: Upload build
  uses: google-github-actions/upload-cloud-storage@v1
    with:
      path: ./dist/blankstorm-client*
      destination: drvortex.dev
      parent: false
```

I'd probably expect something like this:

```yaml
- name: Upload build
  uses: google-github-actions/upload-cloud-storage@v1
    with:
      path: ./dist/blankstorm-client*
      destination: drvortex.dev/${matrix.os}
      parent: false
```
