### ISSUE TITLE
Inconsistent path processing for `.gcloudignore`

### ISSUE THREAD

**Issue by eddielin0926** [google-github-actions/upload-cloud-storage#357]
### TL;DR

The issue pertains to inconsistent path processing when the given path is treated as the root directory, but the top-level `.gcloudignore` is utilized. Therefore, the path in `.gcloudignore` is concatenated with the given path variable.

### Expected behavior

The paths listed in `.gcloudignore` should be calculated from the path of `.gcloudignore`.

### Action YAML

```yaml
- id: 'upload-file'
  uses: 'google-github-actions/upload-cloud-storage@v2'
  with:
    path: '/path/to/file'
    destination: 'bucket-name'
    process_gcloudignore: true
```
