### ISSUE TITLE
the offset is lower than the number of bytes written

### ISSUE THREAD

**Issue by Kepro** [google-github-actions/upload-cloud-storage#363]
### TL;DR

from time to time, our "client" build folder upload fails with
`
Error: google-github-actions/upload-cloud-storage failed with: the offset is lower than the number of bytes written. The server has 0 bytes and while 10 bytes has been uploaded - thus 10 bytes are missing. Stopping as this could result in data loss. Initiate a new upload to continue.
`

but all files are uploaded correctly, rerun always fixed the issue and it really happens randomly

### Action YAML

```yaml
- name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v2

            - name: Upload to Google Cloud storage
              uses: google-github-actions/upload-cloud-storage@v2
              with:
                  path: ./build
                  destination: ${{ env.BUCKET_URL }}
                  parent: false # this will skip creating ./build folder
                  process_gcloudignore: false # we upload everything from build folder
```

### Log output

```text
Run google-github-actions/upload-cloud-storage@v2
  with:
    path: ./build
    destination: XXXX
    parent: false
    process_gcloudignore: false
    gzip: true
    resumable: true
    concurrency: 100

Upload files
  Uploading XXXX
  (... same XXX tiumes


  Error: google-github-actions/upload-cloud-storage failed with: the offset is lower than the number of bytes written. The server has 0 bytes and while 10 bytes has been uploaded - thus 10 bytes are missing. Stopping as this could result in data loss. Initiate a new upload to continue.
```
