### ISSUE TITLE
Reduce api call to token service endpoint

### ISSUE THREAD

**Issue by GregoireW** [google-github-actions/upload-cloud-storage#364]
### TL;DR

When we use this action with workload identity  there is a high number of call made to the token exchange api endpoint. 

![image](https://github.com/user-attachments/assets/49c3721f-a7dd-4be6-b762-7a3d6e5d7964)

By default the exchange token endpoint is rate limited to 6k per minutes. As I got some issue with this limit, I tracked down the usage, and this action is one of the few culprit I found. 

### Additional information

I know this action is using the official  @google-cloud/storage  library, and I'm pretty sure it is something to be fix on this library but I hope it is ok to open this issue here.

**Comment by sethvargo** [comment]
Hi @GregoireW - can you please provide your action.yml so I can reproduce this on my end? Are you seeing that audit log once per object upload? Are you using google-github-actions/auth?

**Comment by GregoireW** [comment]
Hello,

There is not a 1-1 api call - file to be transferred, it may be linked to the parallel things but not sure. 

Here a simple test I use ( I tried direct workload identity and SA workload identity, the result is the same ) : 

```yaml
      - uses: actions/checkout@v4
        id: checkout

      - name: generate
        run: |
          mkdir site
          for i in {1..250} ; do 
            head -c 1M </dev/urandom > site/test-$i.txt ; 
          done;

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: projects/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          service_account: yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

      - name: Publish report
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: ./site
          destination: zzzzzzzzzzzzzzzzzzzzz
          parent: false
          process_gcloudignore: false
          gzip: false
```

I tried to modify this action to use the transfer manager  ( https://github.com/google-github-actions/upload-cloud-storage/compare/main...GregoireW:upload-cloud-storage:main ) , but no luck there apparently
