### ISSUE TITLE
Overwrites all files to one content-type

### ISSUE THREAD

**Issue by mmn0o7** [google-github-actions/upload-cloud-storage#382]
### TL;DR

Uploaded files some were png, some zip... all appear as content-type text/html or whatever the header is set to

### Expected behavior

Preserve file types

### Action YAML

```yaml
- id: 'upload-files'
        if: always()
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'playwright/playwright-report/'
          destination: xxxxxx/${{ github.event.pull_request.number }}/${{ github.run_id }}/${{ github.job }}/${{ matrix.os }}-${{ matrix.testfile }}
          parent: false
```
