### ISSUE TITLE
Upload multiple files

### ISSUE THREAD

**Issue by medoror-mo** [google-github-actions/upload-cloud-storage#386]
### TL;DR

Not sure if this is a bug or a feature request but I want to use this action to upload multiple files in one go. I do NOT want to use glob because there are files of the same file type I do not want uploaded

### Detailed design

I tried the following variants but nothing works with errors about "not finding" files

```
      - name: Upload to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: |
             jsonfile1.json
             jsonfile2.json
          destination: ${{ env.GCS_BUCKET }}/
          parent: false
```

```
      - name: Upload to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: |-
             jsonfile1.json
             jsonfile2.json
          destination: ${{ env.GCS_BUCKET }}/
          parent: false
```
