### ISSUE TITLE
Two-way transfer

### ISSUE THREAD

**Issue by Ameausoone** [google-github-actions/upload-cloud-storage#4]
### TL;DR
This is an action to upload files to cloud storage => couldn't it be a two-way action ? 

### Design

**Action YAML**
It could be a generic `source` => `destination` action. 

```yaml
steps:
  - id: upload-files
    uses: google-github-actions/transfer-cloud-storage@main
    with:
      source: /path/to/folder
      destination: bucket-name
  - id: download-files
    uses: google-github-actions/transfer-cloud-storage@main
    with:
      source: gs://bucket-name/dir/file.txt
      destination: file.txt
```

**Resources**
N/A

**Additional information**
N/A
