### ISSUE TITLE
Parent does not omit path

### ISSUE THREAD

**Issue by eivim** [google-github-actions/upload-cloud-storage#56]
### TL;DR

`parent: false` does not behave as expected.

**Expected behavior**

Only contents of directory specified in `path` is copied to GCS destination.

**Observed behavior**

Parent directory is included, whether `parent` is set to `true` or `false`.

### Reproduction

**Working directory**

```
build/
  foo/some-bundle.js
  bar/other-bundle.js
```

**Action YAML**

```yaml
      - name: Upload to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.gcs_credentials }}
          path: build
          parent: false
          destination: some-bucket.example.com/some/destination
```
